config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'welcome#index'

  resources :portfolios

  resources :about, only: :index

  resources :topics do
    resources :problems do
      resources :solutions
    end
  end

  resources :books do
    resources :book_contents
  end

  resources :blogs do
    collection do
      get :advance_search
    end  
    resources :comments
  end

  resources :rubiests
  resources :pages do
    collection do
      get :contact
      post :create_contact
    end
  end

  resources :downloads, only: :index do
    collection do
      get :downloader
    end
  end

  resources :messages
  resources :studies do
    resources :lessions
  end

  resources :users do
    member do
      get :problems
      get :solutions
    end
  end

  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/lession.rb
class Lession < ApplicationRecord
  include FinderConcern

  belongs_to :user
  belongs_to :study

  scope :active, -> {where(status: true)}

 #****************************************************************************#
  #START Seo Related Functions
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  def slug_candidates
    return if self.title.blank?
    [
      [:title],
      [:title, :id]
    ]
  end
  #END Seo Related Functions

  #Override slug creator method of friendly_id
  def resolve_friendly_id_conflict(candidates)
    candidates.first + friendly_id_config.sequence_separator + SecureRandom.uuid
  end

  #Override slug creator method of friendly_id
  def set_slug(normalized_slug = nil)
    if should_generate_new_friendly_id?
      candidates = FriendlyId::Candidates.new(self, normalized_slug || send(friendly_id_config.base))
      slug = slug_generator.generate(candidates) || resolve_friendly_id_conflict(candidates)
      send "#{friendly_id_config.slug_column}=", slug
    end
  end
#****************************************************************************#  
end

app/controllers/lessions_controller.rb
class LessionsController < ApplicationController
  before_action :set_study, :get_lessions, only: [:index, :show]

  def index
    if @lessions.present?
      @lession = Lession.friendly.find(params[:id].present? ? params[:id] : @lessions.first)
    end
  end

  def show
    
    if @lessions.present?
      @lession = Lession.friendly.find(params[:id].present? ? params[:id] : @lessions.first)
    end
  end

private
    def set_study
      @study = Study.find(params[:study_id])
    end

    def get_lessions
      @lessions = @study.lessions.page(params[:page]).per(10)
    end  
end

app/views/lessions/index.html.erb
<%= render 'shared/header_title', header_title: "", header_sub_title: "Study content releted to #{@study.try(:title)}" %>

<!-- Start row -->
<div class="row">
  <div class="col-md-4 lessions-container">
    <% @lessions.each do |lession| %>
      <%= link_to lession.title, study_lession_path(@study, lession, page: (params[:page] || 1)), class: "lessions-anchor #{"selected" if @lession.id == lession.id}" %>
      <% if lession.featured? %>
        <sup class="featured btn btn-danger btn-xs">Featured</sup>
      <% end %>
      <hr>
    <% end %>
  </div>
  <div class="col-md-8">
    <%= @lession.try(:description).try(:html_safe) %>
  </div>

  <div class="col-sm-12">
    <%= paginate @lessions %>
  </div>
</div>
<!-- /.row -->

app/views/lessions/show.html.erb
<%= render 'shared/header_title', header_title: "", header_sub_title: "Study content releted to #{@study.try(:title)}" %>

<!-- Start row -->
<div class="row">
  <div class="col-md-4 lessions-container">
    <% @lessions.each do |lession| %>
      <%= link_to lession.title, study_lession_path(@study, lession, page: (params[:page] || 1)), class: "lessions-anchor #{"selected" if @lession.id == lession.id}" %>
      <% if lession.featured? %>
        <sup class="featured btn btn-danger btn-xs">Featured</sup>
      <% end %>
      <hr>
    <% end %>
  </div>
  <div class="col-md-8">
    <%= @lession.try(:description).try(:html_safe) %>
  </div>

  <div class="col-sm-12">
    <%= paginate @lessions %>
  </div>
</div>
<!-- /.row -->