config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'welcome#index'

  resources :portfolios

  resources :about, only: :index

  resources :topics do
    resources :problems do
      resources :solutions
    end
  end

  resources :books do
    resources :book_contents
  end

  resources :blogs do
    collection do
      get :advance_search
    end  
    resources :comments
  end

  resources :rubiests
  resources :pages do
    collection do
      get :contact
      post :create_contact
    end
  end

  resources :downloads, only: :index do
    collection do
      get :downloader
    end
  end

  resources :messages
  resources :studies do
    resources :lessions
  end

  resources :users do
    member do
      get :problems
      get :solutions
    end
  end

  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/views/shared/_data_not_found.html.erb
<div class="custom-error text-center">oop's data not found!</div>

app/views/shared/_flash_message.html.erb
<% message, message_class = create_flash_message_and_class %>
<% if message.present? %>
  <div class="alert alert-<%= message_class %> flash_message">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header_title.html.erb
<% if defined?(header_title) && defined?(header_sub_title) %>
  <% content_for :header_title do %>
    <div class="col-lg-12 text-right">
      <h3 class="page-header">
        <%= header_title %>
        <small><%= header_sub_title %></small>
      </h3>
    </div>
  <% end %>
<% end %>

app/views/shared/_meta_data.html.erb
<% meta_options = setup_meta_data(defined?(data) ? data : nil) %>
<% meta title: meta_options[:title], description: meta_options[:description], keywords: meta_options[:keywords] %>
<!-- Sharing image on social like facebook and twitter -->
<% if defined?(image) %>
  <!-- Facebook -->
  <% meta og: { image: image.sub("https", "http") } %>
  <% meta og: { image: {secure_url: image} } %>
  <% meta og: { image: {width: "255"} } %>
  <% meta og: { image: {height: "255"} } %>

  <!-- Twitter -->
  <% meta twitter: { image: image } %>
<% end %>

app/views/shared/_modal.html.erb
<!-- Default bootstrap modal example -->
<div class="modal fade" id="signin-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>

<!-- Advance Search Model -->
<div class="modal fade" id="advance-search-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>

app/views/shared/_page_title.html.erb
<div class="col-lg-12">
  <h1 class="page-header">
    <small>Secondary Text</small>
  </h1>
</div>

app/views/shared/_search_not_found.html.erb
<div class="custom-error text-center">oop's search not found!</div>

app/views/shared/_solution_anchors.html.erb
<div class="row topic-anchor-container">
  <div class="col-sm-12">
    <div class="col-sm-2 border-one anchor-container">
      <%= link_to "Have a problem?", new_topic_problem_path(@topic), class: "topic-anchor" %>
    </div>
    <div class="col-sm-2 border-one anchor-container">
      <%= link_to "Problems", topic_problems_path(@topic), class: "topic-anchor" %>
    </div>
    <% if params[:controller] == "problems" && params[:action] == "show" %>
      <div class="col-sm-2 border-one anchor-container">
        <%= link_to "Your Solution", new_topic_problem_solution_path(@topic, @problem, @solution), class: "topic-anchor", remote: true %>
      </div>
    <% end %>
    <% if params[:controller] == "problems" %>
    <div class="col-sm-3 border-one anchor-container">
      <form action="" class="navbar-form" role="search">
        <div class="input-group add-on">
          <input class="form-control" placeholder="Search" name="search" id="search" type="text" value="<%= params[:search] %>">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
      </form>
    </div>
    <% end %>
  </div>
</div>
<hr>