config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'welcome#index'

  resources :portfolios

  resources :about, only: :index

  resources :topics do
    resources :problems do
      resources :solutions
    end
  end

  resources :books do
    resources :book_contents
  end

  resources :blogs do
    collection do
      get :advance_search
    end  
    resources :comments
  end

  resources :rubiests
  resources :pages do
    collection do
      get :contact
      post :create_contact
    end
  end

  resources :downloads, only: :index do
    collection do
      get :downloader
    end
  end

  resources :messages
  resources :studies do
    resources :lessions
  end

  resources :users do
    member do
      get :problems
      get :solutions
    end
  end

  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<%= render 'shared/header_title', header_title: "", header_sub_title: "Sandeep Maurya's profile" %>
<!-- Row -->
<div class="row">
  <div class="col-md-6 portfolio-item main-page-image">
    <a href="#">
      <% if @user.images.last.present? %>
        <%= image_tag @user.images.last.data.url(:medium), class: "profile-image", alt: @user.username %>
      <% end %>
    </a>
    <div class="spacer-20 clear"></div>
    <%= @user_profile.about[0,100] if @user_profile.present? %>
  </div>

  <div class="col-md-3 portfolio-item main-page-image">
      <%= link_to topics_path do %>
        <%= create_asset_image_template({image_asset_code: "solutions", class: "home-page-image"}) %>
      <% end %>
      <%= link_to "Solutions", topics_path, class: "main-link" %>
      
  </div>
  <div class="col-md-3 portfolio-item main-page-image">
      <%= link_to rubiests_path do %>
        <%= create_asset_image_template({image_asset_code: "programing_is_fun!_as_rubiest", class: "home-page-image"}) %>
      <% end %>
      <%= link_to "Programing is fun! as Rubiest", rubiests_path, class: "main-link" %>
  </div>
</div>
<!-- /.row -->

<!-- Row -->
<div class="row">
  <div class="col-md-3 portfolio-item main-page-image">
    <%= link_to portfolios_path do %>
      <%= create_asset_image_template({image_asset_code: "portfolio", class: "home-page-image"}) %>
    <% end %>
    <%= link_to "Portfolio", portfolios_path, class: "main-link" %>
  </div>

  <div class="col-md-3 portfolio-item main-page-image">
    <%= link_to contact_pages_path do %>
      <%= create_asset_image_template({image_asset_code: "contact", class: "home-page-image"}) %>
    <% end %>
    <%= link_to "Contact Me", contact_pages_path, class: "main-link" %>
  </div>
  <div class="col-md-3 portfolio-item main-page-image">
    <%= link_to blogs_path do %>
      <%= create_asset_image_template({image_asset_code: "blog", class: "home-page-image"}) %>
    <% end %>
    <%= link_to "Blog", blogs_path, class: "main-link" %>
  </div>
  <div class="col-md-3 portfolio-item main-page-image">
    <%= link_to about_index_path do %>
      <%= create_asset_image_template({image_asset_code: "about", class: "home-page-image"}) %>
    <% end %>
    <%= link_to "About Me", about_index_path, class: "main-link" %>
  </div>
</div>
<!-- /.row -->