config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root 'welcome#index'

  resources :portfolios

  resources :about, only: :index

  resources :topics do
    resources :problems do
      resources :solutions
    end
  end

  resources :books do
    resources :book_contents
  end

  resources :blogs do
    collection do
      get :advance_search
    end  
    resources :comments
  end

  resources :rubiests
  resources :pages do
    collection do
      get :contact
      post :create_contact
    end
  end

  resources :downloads, only: :index do
    collection do
      get :downloader
    end
  end

  resources :messages
  resources :studies do
    resources :lessions
  end

  resources :users do
    member do
      get :problems
      get :solutions
    end
  end

  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/study.rb
class Study < ApplicationRecord
  include FinderConcern

  belongs_to :user
  has_many :lessions

  has_many :images, as: :imageable
  accepts_nested_attributes_for :images, allow_destroy: true

  scope :active, -> {where(status: true)}

  def self.study_options
    self.all.map{|study| [study.title, study.id]}
  end

 #****************************************************************************#
  #START Seo Related Functions
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  def slug_candidates
    return if self.title.blank?
    [
      [:title],
      [:title, :id]
    ]
  end
  #END Seo Related Functions

  #Override slug creator method of friendly_id
  def resolve_friendly_id_conflict(candidates)
    candidates.first + friendly_id_config.sequence_separator + SecureRandom.uuid
  end

  #Override slug creator method of friendly_id
  def set_slug(normalized_slug = nil)
    if should_generate_new_friendly_id?
      candidates = FriendlyId::Candidates.new(self, normalized_slug || send(friendly_id_config.base))
      slug = slug_generator.generate(candidates) || resolve_friendly_id_conflict(candidates)
      send "#{friendly_id_config.slug_column}=", slug
    end
  end
#****************************************************************************#
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:edit, :update, :destroy]

  def index
    @studies = Study.all.page(params[:page]).per(10)
  end

private
    def set_study
      @study = Study.find(params[:id])
    end
end

app/views/studies/index.html.erb
<%= render 'shared/header_title', header_title: "", header_sub_title: "Study content" %>

<!-- Start row -->
<div class="row">
  <% @studies.each do |study| %>
    <div class="col-md-6 portfolio-item text-center snm-height-four">
      <a href="<%= study_lessions_path(study) %>">
        <% if study.images.last.present? %>
          <%= image_tag study.images.last.data.url(:original), alt: study.title, class: "snm-image-size-portfolio-one" %>
        <% end %>
      </a>
      <h3>
        <%= link_to study.title, study_lessions_path(study) %>
      </h3>
      <p>
        <%= study.description.try(:html_safe) %>
      </p>
    </div>
  <% end %>
</div>
<!-- /.row -->